config/routes.rb
Rails.application.routes.draw do
  resources :series
  resources :temporadas
  resources :episodios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/episodio.rb
class Episodio < ApplicationRecord
  belongs_to :temporada
end

app/models/serie.rb
class Serie < ApplicationRecord
end

app/models/temporada.rb
class Temporada < ApplicationRecord
  has_many :episodios, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/episodios_controller.rb
class EpisodiosController < ApplicationController
  before_action :set_episodio, only: [:show, :edit, :update, :destroy]

  # GET /episodios
  # GET /episodios.json
  def index
    @episodios = Episodio.all
  end

  # GET /episodios/1
  # GET /episodios/1.json
  def show
  end

  # GET /episodios/new
  def new
    @episodio = Episodio.new
  end

  # GET /episodios/1/edit
  def edit
  end

  # POST /episodios
  # POST /episodios.json
  def create
    @episodio = Episodio.new(episodio_params)

    respond_to do |format|
      if @episodio.save
        format.html { redirect_to @episodio, notice: 'Episodio was successfully created.' }
        format.json { render :show, status: :created, location: @episodio }
      else
        format.html { render :new }
        format.json { render json: @episodio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /episodios/1
  # PATCH/PUT /episodios/1.json
  def update
    respond_to do |format|
      if @episodio.update(episodio_params)
        format.html { redirect_to @episodio, notice: 'Episodio was successfully updated.' }
        format.json { render :show, status: :ok, location: @episodio }
      else
        format.html { render :edit }
        format.json { render json: @episodio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /episodios/1
  # DELETE /episodios/1.json
  def destroy
    @episodio.destroy
    respond_to do |format|
      format.html { redirect_to episodios_url, notice: 'Episodio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_episodio
      @episodio = Episodio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def episodio_params
      params.require(:episodio).permit(:titulo, :sinopse, :assistido, :numero_episodio, :temporada_id)
    end
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  before_action :set_series, only: [:show, :edit, :update, :destroy]

  # GET /series
  # GET /series.json
  def index
    @series = Serie.all
  end

  # GET /series/1
  # GET /series/1.json
  def show
  end

  # GET /series/new
  def new
    @series = Serie.new
  end

  # GET /series/1/edit
  def edit
  end

  # POST /series
  # POST /series.json
  def create
    @series = Serie.new(series_params)

    respond_to do |format|
      if @series.save
        format.html { redirect_to @series, notice: 'Serie was successfully created.' }
        format.json { render :show, status: :created, location: @series }
      else
        format.html { render :new }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /series/1
  # PATCH/PUT /series/1.json
  def update
    respond_to do |format|
      if @series.update(series_params)
        format.html { redirect_to @series, notice: 'Serie was successfully updated.' }
        format.json { render :show, status: :ok, location: @series }
      else
        format.html { render :edit }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /series/1
  # DELETE /series/1.json
  def destroy
    @series.destroy
    respond_to do |format|
      format.html { redirect_to series_url, notice: 'Serie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_series
      @series = Serie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def series_params
      params.require(:series).permit(:titulo, :sinopse)
    end
end

app/controllers/temporadas_controller.rb
class TemporadasController < ApplicationController
  before_action :set_temporada, only: [:show, :edit, :update, :destroy]

  # GET /temporadas
  # GET /temporadas.json
  def index
    @temporadas = Temporada.all
  end

  # GET /temporadas/1
  # GET /temporadas/1.json
  def show
  end

  # GET /temporadas/new
  def new
    @temporada = Temporada.new
  end

  # GET /temporadas/1/edit
  def edit
  end

  # POST /temporadas
  # POST /temporadas.json
  def create
    @temporada = Temporada.new(temporada_params)

    respond_to do |format|
      if @temporada.save
        format.html { redirect_to @temporada, notice: 'Temporada was successfully created.' }
        format.json { render :show, status: :created, location: @temporada }
      else
        format.html { render :new }
        format.json { render json: @temporada.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /temporadas/1
  # PATCH/PUT /temporadas/1.json
  def update
    respond_to do |format|
      if @temporada.update(temporada_params)
        format.html { redirect_to @temporada, notice: 'Temporada was successfully updated.' }
        format.json { render :show, status: :ok, location: @temporada }
      else
        format.html { render :edit }
        format.json { render json: @temporada.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /temporadas/1
  # DELETE /temporadas/1.json
  def destroy
    @temporada.destroy
    respond_to do |format|
      format.html { redirect_to temporadas_url, notice: 'Temporada was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_temporada
      @temporada = Temporada.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def temporada_params
      params.require(:temporada).permit(:numero_temporada)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodios_helper.rb
module EpisodiosHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/helpers/temporadas_helper.rb
module TemporadasHelper
end

app/views/episodios/_form.html.erb
<%= form_for(episodio) do |f| %>
  <% if episodio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(episodio.errors.count, "error") %> prohibited this episodio from being saved:</h2>

      <ul>
      <% episodio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :temporada %>
    <%= collection_select(:episodio,:temporada_id,Temporada.all,:id,:numero_temporada) %>
  </div>

  <div class="field">
    <%= f.label :titulo %>
    <%= f.text_field :titulo %>
  </div>

  <div class="field">
    <%= f.label :sinopse %>
    <%= f.text_area :sinopse %>
  </div>

  <div class="field">
    <%= f.label :assistido %>
    <%= f.check_box :assistido %>
  </div>

  <div class="field">
    <%= f.label :numero_episodio %>
    <%= f.number_field :numero_episodio %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/episodios/edit.html.erb
<h1>Editing Episodio</h1>

<%= render 'form', episodio: @episodio %>

<%= link_to 'Show', @episodio %> |
<%= link_to 'Back', episodios_path %>

app/views/episodios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Episodios</h1>

<table>
  <thead>
    <tr>
      <th>Temporada</th>
      <th>Numero episodio</th>
      <th>Titulo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @episodios.each do |episodio| %>
      <tr>
        <td><%= episodio.temporada.numero_temporada %></td>
        <td><%= episodio.numero_episodio %></td>
        <td><%= episodio.titulo %></td>
        <td><%= link_to 'Show', episodio %></td>
        <td><%= link_to 'Edit', edit_episodio_path(episodio) %></td>
        <td><%= link_to 'Destroy', episodio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Episodio', new_episodio_path %>

app/views/episodios/new.html.erb
<h1>New Episodio</h1>

<%= render 'form', episodio: @episodio %>

<%= link_to 'Back', episodios_path %>

app/views/episodios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @episodio.titulo %>
</p>

<p>
  <strong>Assistido:</strong>
  <%= @episodio.assistido %>
</p>
<p>
  <strong>Temporada:</strong>
  <%= @episodio.temporada.numero_temporada %>
</p>

<p>
  <strong>Numero episodio:</strong>
  <%= @episodio.numero_episodio %>
</p>

<p>
  <strong>Sinopse:</strong>
  <%= @episodio.sinopse %>
</p>


<%= link_to 'Edit', edit_episodio_path(@episodio) %> |
<%= link_to 'Back', episodios_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EP3</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/series/_form.html.erb
<%= form_for(series) do |f| %>
  <% if series.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(series.errors.count, "error") %> prohibited this series from being saved:</h2>

      <ul>
      <% series.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %>
    <%= f.text_field :titulo %>
  </div>

  <div class="field">
    <%= f.label :sinopse %>
    <%= f.text_area :sinopse %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/series/edit.html.erb
<h1>Editing Series</h1>

<%= render 'form', series: @series %>

<%= link_to 'Show', @series %> |
<%= link_to 'Back', series_path %>

app/views/series/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Series</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Sinopse</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @series.each do |series| %>
      <tr>
        <td><%= series.titulo %></td>
        <td><%= series.sinopse %></td>
        <td><%= link_to 'Show', series %></td>
        <td><%= link_to 'Edit', edit_series_path(series) %></td>
        <td><%= link_to 'Destroy', series, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Series', new_series_path %>

app/views/series/new.html.erb
<h1>New Series</h1>

<%= render 'form', series: @series %>

<%= link_to 'Back', series_path %>

app/views/series/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @series.titulo %>
</p>

<p>
  <strong>Sinopse:</strong>
  <%= @series.sinopse %>
</p>

<%= link_to 'Edit', edit_series_path(@series) %> |
<%= link_to 'Back', series_path %>

app/views/temporadas/_form.html.erb
<%= form_for(temporada) do |f| %>
  <% if temporada.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(temporada.errors.count, "error") %> prohibited this temporada from being saved:</h2>

      <ul>
      <% temporada.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :numero_temporada %>
    <%= f.number_field :numero_temporada %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/temporadas/edit.html.erb
<h1>Editing Temporada</h1>

<%= render 'form', temporada: @temporada %>

<%= link_to 'Show', @temporada %> |
<%= link_to 'Back', temporadas_path %>

app/views/temporadas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Temporadas</h1>

<table>
  <thead>
    <tr>
      <th>Numero temporada</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @temporadas.each do |temporada| %>
      <tr>
        <td><%= temporada.numero_temporada %></td>
        <td><%= link_to 'Show', temporada %></td>
        <td><%= link_to 'Edit', edit_temporada_path(temporada) %></td>
        <td><%= link_to 'Destroy', temporada, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Temporada', new_temporada_path %>

app/views/temporadas/new.html.erb
<h1>New Temporada</h1>

<%= render 'form', temporada: @temporada %>

<%= link_to 'Back', temporadas_path %>

app/views/temporadas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Temporada:</strong>
  <%= @temporada.numero_temporada %>
</p>

<p>
  <strong>Episodios:</strong>
  <% @temporada.episodios.each do |episodio| %>
    <p>
      <%= episodio.numero_episodio %>
      <%= episodio.titulo %>
      <%if(episodio.assistido == true)%>
        <%= "Assistido" %>
      <% else %>
        <%= "Pendente" %>
      <% end %>
    </p>
  <% end %>
</p>

<%= link_to 'Edit', edit_temporada_path(@temporada) %> |
<%= link_to 'Back', temporadas_path %>